### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by ComputerScientist-01** [AdityaPrakash-26/ColorDetectionProject#1]
the readme is not self explanatory and needs to be re-written for beginners

**Comment by AdityaPrakash-26** [comment]
Will re-work. Any specific parts where you want to see improvements?

**Comment by ComputerScientist-01** [comment]
could you elaborate on the working part?

**Comment by AdityaPrakash-26** [comment]
Okay. Thanks for the feedback! I will work on it immediately :)

**Comment by AdityaPrakash-26** [comment]
@ComputerScientist-01 I have elaborated on the code and explanation, please check and let me know your feedback! :D

**Comment by ComputerScientist-01** [comment]
it makes more sense now that you have added a link to an article and added more meaningful comments
